### ISSUE TITLE
Better tutorials.. how to draw tiles and sprites?

### ISSUE THREAD

**Issue by salvadorc17** [Stephane-D/SGDK#76] opened 2016-12-19 21:57 UTC
Im trying to understand how to draw tiles and sprites properly but the tutorials are outdated, and some methods used there are deprecated, can you help me telling how to achieve this..

**Comment by Stephane-D** [comment] 2016-12-20 08:43
The best tutorial are the included samples in SGDK, the 'sprite' sample is a good example about how doing basic operations :)

**Comment by Stephane-D** [comment] 2016-12-20 08:43
Duplicate of #5

**Closed by Stephane-D** 2016-12-20 08:43 UTC

**Comment by salvadorc17** [comment] 2016-12-20 20:18
Still outdated, some methods there have wrong arguments and other does not work, you need to update those also..

**Comment by salvadorc17** [comment] 2016-12-20 21:09
Can you tell me why using spr engine does not work properly, when using SPR_update() this give weird colors to image and do not draw sprite.

**Comment by Stephane-D** [comment] 2016-12-21 08:48
There is something probably wrong somewhere in the code.
Did you have uploaded the palette manually before ? Did you correctly initialized the Sprite engine ?
Use http://gendev.spritesmind.net/forum/ forum to have support, you will find tons of help / answer about SGDK use :)

**Comment by salvadorc17** [comment] 2016-12-21 20:57
You mean vdp_setpallete and spr_init(), yes i have used those, the bitmaps draw properly, but when using spr_update the thing got broken.

**Comment by s7jones** [comment] 2017-02-06 23:13
I've not been able to adapt my old files based on the outdated tutorial to the new changes to SGDK. I'd be interested in a redone tutorial too. Thanks.

**Comment by Stephane-D** [comment] 2017-02-07 12:38
I will try to definitely update them on next big SGDK update !
Unfortunately i'm really busy both with my professional and private life now, as soon i've a bit of spare time i will get back working on SGDK :)
