### ISSUE TITLE
Big sprites do not display correctly

### ISSUE THREAD

**Issue by gilvanmaia** [Stephane-D/SGDK#31] opened 2015-06-10 18:32 UTC
Hi there.

I'm trying to insert a sprite that is 13x13 tiles big. Data seems to be OK, but as soon as an animation is changed, the sprite partially blinks and also displays some bad tiles.

Is there something important that I am missing or is it really a bug?
By the way, I made some slides about basic function usage etc and could send these to you.

PS: did not find your e-mail therefore I am sending this message.

**Comment by Stephane-D** [comment] 2015-06-11 08:33
A 13x13 tiles sprite should fit in the sprite size limit of SGDK (which is a maximum of 20 hardware sprites and here you need 16). It may be related to the sprite cache size but if the first sprite frame is ok then it should be able to display other frame as well.
Can you provide me s small test sample so i can reproduce the problem ?

Also i would be really glad to put your slides as part of the SGDK tutorial ! As you may have noticed current tutorials are outdated and minimalists :-/

**Comment by gilvanmaia** [comment] 2015-06-11 17:00
Wow, that reply was really fast. =)
Sorry about my timing, but we got a blackout yesterday and the internet got really slow.

Here goes more detail:
 - every frame in my spritesheet has 13x13 tiles, and a total of 8 animations. These are for initial tests  aiming to build a fighting game or a "beat them up";
 - the longer animation is a walking sequence with 8 frames;
 - confirmed that problems occur when the animation changes.
 
First I tried to insert the sprite directly in my code. When the error occured, I assumed it was a problem with the code I wrote, and decided to test things in the sprite sample.
Here is the result:
![2dellalonge](https://cloud.githubusercontent.com/assets/9355053/8112991/b69c306c-1041-11e5-9b2f-1a92ac59f548.png)

I thought it may be the cache size. I tried to increase it to 512 and the problem was still in there.
Just let me get permission from the artist to send you the original image.

Best regards, and I will come back soon.

**Comment by gilvanmaia** [comment] 2015-06-11 17:17
Hello again,  

=D

This is the original spritesheet.
![gilz](https://cloud.githubusercontent.com/assets/9355053/8113358/f1a7ebae-1043-11e5-9180-48ad6003c6db.png)

And this is the rescaled spritesheet (no care at all with art adjustments here, of course):

![gil_48](https://cloud.githubusercontent.com/assets/9355053/8113399/3a9952e4-1044-11e5-9008-4ce6aab418db.png)

Let me know whether there is problems and how to fix them.
I will do my best to explain how users can avoid such problem.

Thank you in advance,

**Comment by Stephane-D** [comment] 2015-06-14 20:53
Thanks for the sprite sheet :) I just tested in the sprite example and i can reproduce the problem if i keep sprite size cache to 256 but the problem disappears if i use `SPR_init((13*13*2) + 100)` for instance. But i modified the sprite code a bit in my WIP, that may explain the difference. Anyway even at 256 we should have enough tiles and i noticed some others update bug so i will investigate that :)
Thanks for reporting ! By the way in the meantime, try also to disable the compression for the sprite as it consume a lot of cpu time ;)

**Comment by gilvanmaia** [comment] 2015-06-16 14:34
Thanks for all those tips. Works just fine now. 

I just can't wait until you relase your WIP.
Please excuse me in advance for deleting the spritesheet from the previous posts.  
It does not belong to me, so I think this is the right thing to do.

Congrats for the amazing work.

PS: sorry 'bout the delayed reply. Yesterday was a crazy day.

**Comment by Stephane-D** [comment] 2015-06-16 14:40
No worries ! I now these crazy days as well ;)
Also because of that i think the next SGDK version won't come that soon, i hope to make a good set of changes so that will definitely take sometime !

**Comment by gilvanmaia** [comment] 2016-03-15 18:04
Hi again! Sorry for being late on this topic.

1) Here is my e-mail address: gilvanmaia@virtual.ufc.br

2) If you would like, here is the GIMP plugin I told you about before. Each animation corresponds to a layer group, so each successive frame is stored by individual layers.

Feel free to redistribute it along SGDK:
http://tejo.virtual.ufc.br/md/tejo-spritesheet-0.3.py

Here is a sample animation image:
tejo.virtual.ufc.br/md/tejo-star.xcf

=D

**Comment by Stephane-D** [comment] 2016-05-30 10:38
Fixed with the new sprite engine.

**Closed by Stephane-D** 2016-05-30 10:38 UTC
Labels: bug, Priority-High

**Comment by gilvanmaia** [comment] 2016-05-30 11:53
Congrats! \o/
